//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahalaxmiMarbal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Mahalaxmi_MarbelsEntities : DbContext
    {
        public Mahalaxmi_MarbelsEntities()
            : base("name=Mahalaxmi_MarbelsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tabel_Customer> Tabel_Customer { get; set; }
        public virtual DbSet<Table_Bill> Table_Bill { get; set; }
        public virtual DbSet<Table_OrderDeatils> Table_OrderDeatils { get; set; }
        public virtual DbSet<Table_Product> Table_Product { get; set; }
        public virtual DbSet<Table_ProductDetails> Table_ProductDetails { get; set; }
        public virtual DbSet<Table_Registration> Table_Registration { get; set; }
        public virtual DbSet<Table_Vendor_Registration> Table_Vendor_Registration { get; set; }
    }
}
