//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahalaxmiMarbal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabel_Customer
    {
        public int Cust_Id { get; set; }
        public string CustName { get; set; }
        public string CustPh { get; set; }
        public string CustAddress { get; set; }
        public string CustEmail { get; set; }
        public string Date { get; set; }
    }
}
