//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahalaxmiMarbal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Product()
        {
            this.Table_ProductDetails = new HashSet<Table_ProductDetails>();
        }
    
        public int Product_id { get; set; }
        public string PName { get; set; }
        public string CreatedDate { get; set; }
        public string UpdatedDate { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_ProductDetails> Table_ProductDetails { get; set; }
    }
}
