//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahalaxmiMarbal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_OrderDeatils
    {
        public int Id { get; set; }
        public Nullable<int> ProductDetailsId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string TotalAmount { get; set; }
        public string TotalDiscount { get; set; }
        public string FinalAmount { get; set; }
    }
}
