//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahalaxmiMarbal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Vendor_Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Vendor_Registration()
        {
            this.Table_ProductDetails = new HashSet<Table_ProductDetails>();
        }
    
        public int Vendor_id { get; set; }
        public string Vendor_Name { get; set; }
        public string Shop_Name { get; set; }
        public string Vendor_Phone { get; set; }
        public string Shop_Phone { get; set; }
        public string Shop_Address { get; set; }
        public string Vendor_Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_ProductDetails> Table_ProductDetails { get; set; }
    }
}
